name = "SimpleTwitterAnalyzer"
uuid = "f1f44c16-6a52-11e9-280b-b5fd0c072bd7"
authors = ["aleant93 <aless.antelmi@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
